version: "3.8"
services:
  nudgarr:
    image: ghcr.io/mmagtech/nudgarr:latest
    container_name: nudgarr
    restart: unless-stopped
    ports:
      - "8085:8085"
    volumes:
      - /mnt/user/appdata/nudgarr:/config
    environment:
      - PORT=8085
      - CONFIG_FILE=/config/nudgarr-config.json
      - STATE_FILE=/config/nudgarr-state.json
